# Generated by Django 5.1 on 2024-08-23 17:28

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Описание про библиотеку')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('time_work', models.CharField(max_length=100, verbose_name='Время работы')),
                ('video_link', models.CharField(blank=True, max_length=100, verbose_name='Видео ссылка')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/', verbose_name='Аудио')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Рейтинг')),
                ('num_votes', models.PositiveIntegerField(default=0, verbose_name='Количество голосов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Районы города Бишкек')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
            },
        ),
        migrations.CreateModel(
            name='BranchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/branch_images', verbose_name='Изображение')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cls.branch', verbose_name='Филиал')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cls.region', verbose_name='Район'),
        ),
    ]
